# Generated by Django 5.0.4 on 2024-06-20 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cereals',
            name='product',
        ),
        migrations.RemoveField(
            model_name='dairy',
            name='product',
        ),
        migrations.RemoveField(
            model_name='drinks',
            name='product',
        ),
        migrations.RemoveField(
            model_name='meat',
            name='product',
        ),
        migrations.RemoveField(
            model_name='seafood',
            name='product',
        ),
        migrations.RemoveField(
            model_name='snacks',
            name='product',
        ),
        migrations.RemoveField(
            model_name='species',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tea',
            name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='prod',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveIntegerField(choices=[(1, 'Dairy'), (2, 'Bread'), (3, 'Meat'), (4, 'Fish/Seafood'), (5, 'Drinks'), (6, 'Snacks'), (7, 'Tea/Coffee'), (8, 'Species/Sauces'), (9, 'Ceareals')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Bread',
        ),
        migrations.DeleteModel(
            name='Cereals',
        ),
        migrations.DeleteModel(
            name='Dairy',
        ),
        migrations.DeleteModel(
            name='Drinks',
        ),
        migrations.DeleteModel(
            name='Meat',
        ),
        migrations.DeleteModel(
            name='Seafood',
        ),
        migrations.DeleteModel(
            name='Snacks',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.DeleteModel(
            name='Tea',
        ),
    ]
